// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: project.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectStatus int32

const (
	ProjectStatus_PROJECT_STATUS_UNSPECIFIED ProjectStatus = 0
	ProjectStatus_PROJECT_STATUS_IN_WORK     ProjectStatus = 1
	ProjectStatus_PROJECT_STATUS_ENDED       ProjectStatus = 2
)

// Enum value maps for ProjectStatus.
var (
	ProjectStatus_name = map[int32]string{
		0: "PROJECT_STATUS_UNSPECIFIED",
		1: "PROJECT_STATUS_IN_WORK",
		2: "PROJECT_STATUS_ENDED",
	}
	ProjectStatus_value = map[string]int32{
		"PROJECT_STATUS_UNSPECIFIED": 0,
		"PROJECT_STATUS_IN_WORK":     1,
		"PROJECT_STATUS_ENDED":       2,
	}
)

func (x ProjectStatus) Enum() *ProjectStatus {
	p := new(ProjectStatus)
	*p = x
	return p
}

func (x ProjectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_project_proto_enumTypes[0].Descriptor()
}

func (ProjectStatus) Type() protoreflect.EnumType {
	return &file_project_proto_enumTypes[0]
}

func (x ProjectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectStatus.Descriptor instead.
func (ProjectStatus) EnumDescriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{0}
}

type TaskPriority int32

const (
	TaskPriority_TASK_PRIORITY_UNSPECIFIED TaskPriority = 0
	TaskPriority_TASK_PRIORITY_LOW         TaskPriority = 1
	TaskPriority_TASK_PRIORITY_MEDIUM      TaskPriority = 2
	TaskPriority_TASK_PRIORITY_HIGH        TaskPriority = 3
)

// Enum value maps for TaskPriority.
var (
	TaskPriority_name = map[int32]string{
		0: "TASK_PRIORITY_UNSPECIFIED",
		1: "TASK_PRIORITY_LOW",
		2: "TASK_PRIORITY_MEDIUM",
		3: "TASK_PRIORITY_HIGH",
	}
	TaskPriority_value = map[string]int32{
		"TASK_PRIORITY_UNSPECIFIED": 0,
		"TASK_PRIORITY_LOW":         1,
		"TASK_PRIORITY_MEDIUM":      2,
		"TASK_PRIORITY_HIGH":        3,
	}
)

func (x TaskPriority) Enum() *TaskPriority {
	p := new(TaskPriority)
	*p = x
	return p
}

func (x TaskPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_project_proto_enumTypes[1].Descriptor()
}

func (TaskPriority) Type() protoreflect.EnumType {
	return &file_project_proto_enumTypes[1]
}

func (x TaskPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskPriority.Descriptor instead.
func (TaskPriority) EnumDescriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{1}
}

type TaskDifficulty int32

const (
	TaskDifficulty_TASK_DIFFICULTY_UNSPECIFIED TaskDifficulty = 0
	TaskDifficulty_TASK_DIFFICULTY_EASY        TaskDifficulty = 1
	TaskDifficulty_TASK_DIFFICULTY_MEDIUM      TaskDifficulty = 2
	TaskDifficulty_TASK_DIFFICULTY_HARD        TaskDifficulty = 3
)

// Enum value maps for TaskDifficulty.
var (
	TaskDifficulty_name = map[int32]string{
		0: "TASK_DIFFICULTY_UNSPECIFIED",
		1: "TASK_DIFFICULTY_EASY",
		2: "TASK_DIFFICULTY_MEDIUM",
		3: "TASK_DIFFICULTY_HARD",
	}
	TaskDifficulty_value = map[string]int32{
		"TASK_DIFFICULTY_UNSPECIFIED": 0,
		"TASK_DIFFICULTY_EASY":        1,
		"TASK_DIFFICULTY_MEDIUM":      2,
		"TASK_DIFFICULTY_HARD":        3,
	}
)

func (x TaskDifficulty) Enum() *TaskDifficulty {
	p := new(TaskDifficulty)
	*p = x
	return p
}

func (x TaskDifficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskDifficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_project_proto_enumTypes[2].Descriptor()
}

func (TaskDifficulty) Type() protoreflect.EnumType {
	return &file_project_proto_enumTypes[2]
}

func (x TaskDifficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskDifficulty.Descriptor instead.
func (TaskDifficulty) EnumDescriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{2}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_NOT_STARTED TaskStatus = 1
	TaskStatus_TASK_STATUS_IN_WORK     TaskStatus = 2
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_NOT_STARTED",
		2: "TASK_STATUS_IN_WORK",
		3: "TASK_STATUS_COMPLETED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_NOT_STARTED": 1,
		"TASK_STATUS_IN_WORK":     2,
		"TASK_STATUS_COMPLETED":   3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_project_proto_enumTypes[3].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_project_proto_enumTypes[3]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{3}
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ManagerId     int32                  `protobuf:"varint,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        ProjectStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=dto.ProjectStatus" json:"status,omitempty"`
	StartDate     string                 `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *string                `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Project) GetManagerId() int32 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetStatus() ProjectStatus {
	if x != nil {
		return x.Status
	}
	return ProjectStatus_PROJECT_STATUS_UNSPECIFIED
}

func (x *Project) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Project) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     int32                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AssigneeId    *int32                 `protobuf:"varint,3,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Priority      TaskPriority           `protobuf:"varint,6,opt,name=priority,proto3,enum=dto.TaskPriority" json:"priority,omitempty"`
	Difficulty    TaskDifficulty         `protobuf:"varint,7,opt,name=difficulty,proto3,enum=dto.TaskDifficulty" json:"difficulty,omitempty"`
	Status        TaskStatus             `protobuf:"varint,8,opt,name=status,proto3,enum=dto.TaskStatus" json:"status,omitempty"`
	StartDate     *string                `protobuf:"bytes,9,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate       *string                `protobuf:"bytes,10,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *Task) GetAssigneeId() int32 {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return 0
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Task) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *Task) GetDifficulty() TaskDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return TaskDifficulty_TASK_DIFFICULTY_UNSPECIFIED
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *Task) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      int32                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	TaskId        int32                  `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreationDate  string                 `protobuf:"bytes,5,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{2}
}

func (x *Comment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Comment) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProjectResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DashboardResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnedProjects  []*Project             `protobuf:"bytes,1,rep,name=owned_projects,json=ownedProjects,proto3" json:"owned_projects,omitempty"`
	MemberProjects []*Project             `protobuf:"bytes,2,rep,name=member_projects,json=memberProjects,proto3" json:"member_projects,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DashboardResponse) Reset() {
	*x = DashboardResponse{}
	mi := &file_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardResponse) ProtoMessage() {}

func (x *DashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardResponse.ProtoReflect.Descriptor instead.
func (*DashboardResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{5}
}

func (x *DashboardResponse) GetOwnedProjects() []*Project {
	if x != nil {
		return x.OwnedProjects
	}
	return nil
}

func (x *DashboardResponse) GetMemberProjects() []*Project {
	if x != nil {
		return x.MemberProjects
	}
	return nil
}

type TasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasksResponse) Reset() {
	*x = TasksResponse{}
	mi := &file_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksResponse) ProtoMessage() {}

func (x *TasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksResponse.ProtoReflect.Descriptor instead.
func (*TasksResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{6}
}

func (x *TasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ProjectMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*User                `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMembersResponse) Reset() {
	*x = ProjectMembersResponse{}
	mi := &file_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMembersResponse) ProtoMessage() {}

func (x *ProjectMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMembersResponse.ProtoReflect.Descriptor instead.
func (*ProjectMembersResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectMembersResponse) GetMembers() []*User {
	if x != nil {
		return x.Members
	}
	return nil
}

type ProjectMemberIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []int32                `protobuf:"varint,1,rep,packed,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberIdsResponse) Reset() {
	*x = ProjectMemberIdsResponse{}
	mi := &file_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberIdsResponse) ProtoMessage() {}

func (x *ProjectMemberIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberIdsResponse.ProtoReflect.Descriptor instead.
func (*ProjectMemberIdsResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectMemberIdsResponse) GetMembers() []int32 {
	if x != nil {
		return x.Members
	}
	return nil
}

type UserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdResponse) Reset() {
	*x = UserIdResponse{}
	mi := &file_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdResponse) ProtoMessage() {}

func (x *UserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdResponse.ProtoReflect.Descriptor instead.
func (*UserIdResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{9}
}

func (x *UserIdResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type IsManagerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsManager     bool                   `protobuf:"varint,1,opt,name=is_manager,json=isManager,proto3" json:"is_manager,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsManagerResponse) Reset() {
	*x = IsManagerResponse{}
	mi := &file_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsManagerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsManagerResponse) ProtoMessage() {}

func (x *IsManagerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsManagerResponse.ProtoReflect.Descriptor instead.
func (*IsManagerResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{10}
}

func (x *IsManagerResponse) GetIsManager() bool {
	if x != nil {
		return x.IsManager
	}
	return false
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int32                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Priority      TaskPriority           `protobuf:"varint,4,opt,name=priority,proto3,enum=dto.TaskPriority" json:"priority,omitempty"`
	Difficulty    TaskDifficulty         `protobuf:"varint,5,opt,name=difficulty,proto3,enum=dto.TaskDifficulty" json:"difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{11}
}

func (x *CreateTaskRequest) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *CreateTaskRequest) GetDifficulty() TaskDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return TaskDifficulty_TASK_DIFFICULTY_UNSPECIFIED
}

type AssignTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssigneeId    int32                  `protobuf:"varint,1,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTaskRequest) Reset() {
	*x = AssignTaskRequest{}
	mi := &file_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTaskRequest) ProtoMessage() {}

func (x *AssignTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTaskRequest.ProtoReflect.Descriptor instead.
func (*AssignTaskRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{12}
}

func (x *AssignTaskRequest) GetAssigneeId() int32 {
	if x != nil {
		return x.AssigneeId
	}
	return 0
}

type UpdateTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TaskStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=dto.TaskStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusRequest) Reset() {
	*x = UpdateTaskStatusRequest{}
	mi := &file_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusRequest) ProtoMessage() {}

func (x *UpdateTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateTaskStatusRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

type IsUserManagerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsManager     bool                   `protobuf:"varint,1,opt,name=is_manager,json=isManager,proto3" json:"is_manager,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUserManagerResponse) Reset() {
	*x = IsUserManagerResponse{}
	mi := &file_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUserManagerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserManagerResponse) ProtoMessage() {}

func (x *IsUserManagerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserManagerResponse.ProtoReflect.Descriptor instead.
func (*IsUserManagerResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{14}
}

func (x *IsUserManagerResponse) GetIsManager() bool {
	if x != nil {
		return x.IsManager
	}
	return false
}

var File_project_proto protoreflect.FileDescriptor

const file_project_proto_rawDesc = "" +
	"\n" +
	"\rproject.proto\x12\x03dto\x1a\n" +
	"user.proto\"\xe6\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x02 \x01(\x05R\tmanagerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12*\n" +
	"\x06status\x18\x05 \x01(\x0e2\x12.dto.ProjectStatusR\x06status\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x1e\n" +
	"\bend_date\x18\a \x01(\tH\x00R\aendDate\x88\x01\x01B\v\n" +
	"\t_end_date\"\xa3\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x05R\tprojectId\x12$\n" +
	"\vassignee_id\x18\x03 \x01(\x05H\x00R\n" +
	"assigneeId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x01R\vdescription\x88\x01\x01\x12-\n" +
	"\bpriority\x18\x06 \x01(\x0e2\x11.dto.TaskPriorityR\bpriority\x123\n" +
	"\n" +
	"difficulty\x18\a \x01(\x0e2\x13.dto.TaskDifficultyR\n" +
	"difficulty\x12'\n" +
	"\x06status\x18\b \x01(\x0e2\x0f.dto.TaskStatusR\x06status\x12\"\n" +
	"\n" +
	"start_date\x18\t \x01(\tH\x02R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\n" +
	" \x01(\tH\x03R\aendDate\x88\x01\x01B\x0e\n" +
	"\f_assignee_idB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_date\"\x8e\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x05R\bauthorId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x05R\x06taskId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12#\n" +
	"\rcreation_date\x18\x05 \x01(\tR\fcreationDate\"L\n" +
	"\x14CreateProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"'\n" +
	"\x15CreateProjectResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x7f\n" +
	"\x11DashboardResponse\x123\n" +
	"\x0eowned_projects\x18\x01 \x03(\v2\f.dto.ProjectR\rownedProjects\x125\n" +
	"\x0fmember_projects\x18\x02 \x03(\v2\f.dto.ProjectR\x0ememberProjects\"0\n" +
	"\rTasksResponse\x12\x1f\n" +
	"\x05tasks\x18\x01 \x03(\v2\t.dto.TaskR\x05tasks\"=\n" +
	"\x16ProjectMembersResponse\x12#\n" +
	"\amembers\x18\x01 \x03(\v2\t.dto.UserR\amembers\"4\n" +
	"\x18ProjectMemberIdsResponse\x12\x18\n" +
	"\amembers\x18\x01 \x03(\x05R\amembers\")\n" +
	"\x0eUserIdResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"2\n" +
	"\x11IsManagerResponse\x12\x1d\n" +
	"\n" +
	"is_manager\x18\x01 \x01(\bR\tisManager\"\xe1\x01\n" +
	"\x11CreateTaskRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x05R\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12-\n" +
	"\bpriority\x18\x04 \x01(\x0e2\x11.dto.TaskPriorityR\bpriority\x123\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x0e2\x13.dto.TaskDifficultyR\n" +
	"difficultyB\x0e\n" +
	"\f_description\"4\n" +
	"\x11AssignTaskRequest\x12\x1f\n" +
	"\vassignee_id\x18\x01 \x01(\x05R\n" +
	"assigneeId\"B\n" +
	"\x17UpdateTaskStatusRequest\x12'\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0f.dto.TaskStatusR\x06status\"6\n" +
	"\x15IsUserManagerResponse\x12\x1d\n" +
	"\n" +
	"is_manager\x18\x01 \x01(\bR\tisManager*e\n" +
	"\rProjectStatus\x12\x1e\n" +
	"\x1aPROJECT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PROJECT_STATUS_IN_WORK\x10\x01\x12\x18\n" +
	"\x14PROJECT_STATUS_ENDED\x10\x02*v\n" +
	"\fTaskPriority\x12\x1d\n" +
	"\x19TASK_PRIORITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_PRIORITY_LOW\x10\x01\x12\x18\n" +
	"\x14TASK_PRIORITY_MEDIUM\x10\x02\x12\x16\n" +
	"\x12TASK_PRIORITY_HIGH\x10\x03*\x81\x01\n" +
	"\x0eTaskDifficulty\x12\x1f\n" +
	"\x1bTASK_DIFFICULTY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TASK_DIFFICULTY_EASY\x10\x01\x12\x1a\n" +
	"\x16TASK_DIFFICULTY_MEDIUM\x10\x02\x12\x18\n" +
	"\x14TASK_DIFFICULTY_HARD\x10\x03*z\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TASK_STATUS_NOT_STARTED\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_IN_WORK\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x03B(Z&project-service/internal/model/dto;dtob\x06proto3"

var (
	file_project_proto_rawDescOnce sync.Once
	file_project_proto_rawDescData []byte
)

func file_project_proto_rawDescGZIP() []byte {
	file_project_proto_rawDescOnce.Do(func() {
		file_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_proto_rawDesc), len(file_project_proto_rawDesc)))
	})
	return file_project_proto_rawDescData
}

var file_project_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_project_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_project_proto_goTypes = []any{
	(ProjectStatus)(0),               // 0: dto.ProjectStatus
	(TaskPriority)(0),                // 1: dto.TaskPriority
	(TaskDifficulty)(0),              // 2: dto.TaskDifficulty
	(TaskStatus)(0),                  // 3: dto.TaskStatus
	(*Project)(nil),                  // 4: dto.Project
	(*Task)(nil),                     // 5: dto.Task
	(*Comment)(nil),                  // 6: dto.Comment
	(*CreateProjectRequest)(nil),     // 7: dto.CreateProjectRequest
	(*CreateProjectResponse)(nil),    // 8: dto.CreateProjectResponse
	(*DashboardResponse)(nil),        // 9: dto.DashboardResponse
	(*TasksResponse)(nil),            // 10: dto.TasksResponse
	(*ProjectMembersResponse)(nil),   // 11: dto.ProjectMembersResponse
	(*ProjectMemberIdsResponse)(nil), // 12: dto.ProjectMemberIdsResponse
	(*UserIdResponse)(nil),           // 13: dto.UserIdResponse
	(*IsManagerResponse)(nil),        // 14: dto.IsManagerResponse
	(*CreateTaskRequest)(nil),        // 15: dto.CreateTaskRequest
	(*AssignTaskRequest)(nil),        // 16: dto.AssignTaskRequest
	(*UpdateTaskStatusRequest)(nil),  // 17: dto.UpdateTaskStatusRequest
	(*IsUserManagerResponse)(nil),    // 18: dto.IsUserManagerResponse
	(*User)(nil),                     // 19: dto.User
}
var file_project_proto_depIdxs = []int32{
	0,  // 0: dto.Project.status:type_name -> dto.ProjectStatus
	1,  // 1: dto.Task.priority:type_name -> dto.TaskPriority
	2,  // 2: dto.Task.difficulty:type_name -> dto.TaskDifficulty
	3,  // 3: dto.Task.status:type_name -> dto.TaskStatus
	4,  // 4: dto.DashboardResponse.owned_projects:type_name -> dto.Project
	4,  // 5: dto.DashboardResponse.member_projects:type_name -> dto.Project
	5,  // 6: dto.TasksResponse.tasks:type_name -> dto.Task
	19, // 7: dto.ProjectMembersResponse.members:type_name -> dto.User
	1,  // 8: dto.CreateTaskRequest.priority:type_name -> dto.TaskPriority
	2,  // 9: dto.CreateTaskRequest.difficulty:type_name -> dto.TaskDifficulty
	3,  // 10: dto.UpdateTaskStatusRequest.status:type_name -> dto.TaskStatus
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_project_proto_init() }
func file_project_proto_init() {
	if File_project_proto != nil {
		return
	}
	file_user_proto_init()
	file_project_proto_msgTypes[0].OneofWrappers = []any{}
	file_project_proto_msgTypes[1].OneofWrappers = []any{}
	file_project_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_proto_rawDesc), len(file_project_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_project_proto_goTypes,
		DependencyIndexes: file_project_proto_depIdxs,
		EnumInfos:         file_project_proto_enumTypes,
		MessageInfos:      file_project_proto_msgTypes,
	}.Build()
	File_project_proto = out.File
	file_project_proto_goTypes = nil
	file_project_proto_depIdxs = nil
}
