// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: project_service.proto

package projectsvcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	projectv1 "project-service/api/proto/projectv1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_project_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_project_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_project_service_proto_rawDescGZIP(), []int{0}
}

type ProjectIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int32                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectIdRequest) Reset() {
	*x = ProjectIdRequest{}
	mi := &file_project_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectIdRequest) ProtoMessage() {}

func (x *ProjectIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectIdRequest.ProtoReflect.Descriptor instead.
func (*ProjectIdRequest) Descriptor() ([]byte, []int) {
	return file_project_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectIdRequest) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type TaskIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskIdRequest) Reset() {
	*x = TaskIdRequest{}
	mi := &file_project_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskIdRequest) ProtoMessage() {}

func (x *TaskIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskIdRequest.ProtoReflect.Descriptor instead.
func (*TaskIdRequest) Descriptor() ([]byte, []int) {
	return file_project_service_proto_rawDescGZIP(), []int{2}
}

func (x *TaskIdRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type UserProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProjectsRequest) Reset() {
	*x = UserProjectsRequest{}
	mi := &file_project_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProjectsRequest) ProtoMessage() {}

func (x *UserProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProjectsRequest.ProtoReflect.Descriptor instead.
func (*UserProjectsRequest) Descriptor() ([]byte, []int) {
	return file_project_service_proto_rawDescGZIP(), []int{3}
}

func (x *UserProjectsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int32                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_project_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_project_service_proto_rawDescGZIP(), []int{4}
}

func (x *AddMemberRequest) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *AddMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type TransferManagerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int32                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	NewManagerId  int32                  `protobuf:"varint,2,opt,name=new_manager_id,json=newManagerId,proto3" json:"new_manager_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferManagerRequest) Reset() {
	*x = TransferManagerRequest{}
	mi := &file_project_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferManagerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferManagerRequest) ProtoMessage() {}

func (x *TransferManagerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferManagerRequest.ProtoReflect.Descriptor instead.
func (*TransferManagerRequest) Descriptor() ([]byte, []int) {
	return file_project_service_proto_rawDescGZIP(), []int{5}
}

func (x *TransferManagerRequest) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *TransferManagerRequest) GetNewManagerId() int32 {
	if x != nil {
		return x.NewManagerId
	}
	return 0
}

type IsManagerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int32                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsManagerRequest) Reset() {
	*x = IsManagerRequest{}
	mi := &file_project_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsManagerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsManagerRequest) ProtoMessage() {}

func (x *IsManagerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsManagerRequest.ProtoReflect.Descriptor instead.
func (*IsManagerRequest) Descriptor() ([]byte, []int) {
	return file_project_service_proto_rawDescGZIP(), []int{6}
}

func (x *IsManagerRequest) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type UpdateTaskStatusGrpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        projectv1.TaskStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=projectv1.TaskStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusGrpcRequest) Reset() {
	*x = UpdateTaskStatusGrpcRequest{}
	mi := &file_project_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusGrpcRequest) ProtoMessage() {}

func (x *UpdateTaskStatusGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusGrpcRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusGrpcRequest) Descriptor() ([]byte, []int) {
	return file_project_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTaskStatusGrpcRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *UpdateTaskStatusGrpcRequest) GetStatus() projectv1.TaskStatus {
	if x != nil {
		return x.Status
	}
	return projectv1.TaskStatus(0)
}

type AssignTaskGrpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AssigneeId    int32                  `protobuf:"varint,2,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTaskGrpcRequest) Reset() {
	*x = AssignTaskGrpcRequest{}
	mi := &file_project_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTaskGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTaskGrpcRequest) ProtoMessage() {}

func (x *AssignTaskGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTaskGrpcRequest.ProtoReflect.Descriptor instead.
func (*AssignTaskGrpcRequest) Descriptor() ([]byte, []int) {
	return file_project_service_proto_rawDescGZIP(), []int{8}
}

func (x *AssignTaskGrpcRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *AssignTaskGrpcRequest) GetAssigneeId() int32 {
	if x != nil {
		return x.AssigneeId
	}
	return 0
}

type CreateCommentGrpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentGrpcRequest) Reset() {
	*x = CreateCommentGrpcRequest{}
	mi := &file_project_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentGrpcRequest) ProtoMessage() {}

func (x *CreateCommentGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentGrpcRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentGrpcRequest) Descriptor() ([]byte, []int) {
	return file_project_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCommentGrpcRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CreateCommentGrpcRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateCommentGrpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CommentId     int32                  `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentGrpcRequest) Reset() {
	*x = UpdateCommentGrpcRequest{}
	mi := &file_project_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentGrpcRequest) ProtoMessage() {}

func (x *UpdateCommentGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentGrpcRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentGrpcRequest) Descriptor() ([]byte, []int) {
	return file_project_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCommentGrpcRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *UpdateCommentGrpcRequest) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *UpdateCommentGrpcRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DeleteCommentGrpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CommentId     int32                  `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentGrpcRequest) Reset() {
	*x = DeleteCommentGrpcRequest{}
	mi := &file_project_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentGrpcRequest) ProtoMessage() {}

func (x *DeleteCommentGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentGrpcRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentGrpcRequest) Descriptor() ([]byte, []int) {
	return file_project_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCommentGrpcRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *DeleteCommentGrpcRequest) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

var File_project_service_proto protoreflect.FileDescriptor

const file_project_service_proto_rawDesc = "" +
	"\n" +
	"\x15project_service.proto\x12\fprojectsvcv1\x1a\rproject.proto\"\a\n" +
	"\x05Empty\"1\n" +
	"\x10ProjectIdRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x05R\tprojectId\"(\n" +
	"\rTaskIdRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\".\n" +
	"\x13UserProjectsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"G\n" +
	"\x10AddMemberRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x05R\tprojectId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"]\n" +
	"\x16TransferManagerRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x05R\tprojectId\x12$\n" +
	"\x0enew_manager_id\x18\x02 \x01(\x05R\fnewManagerId\"1\n" +
	"\x10IsManagerRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x05R\tprojectId\"e\n" +
	"\x1bUpdateTaskStatusGrpcRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.projectv1.TaskStatusR\x06status\"Q\n" +
	"\x15AssignTaskGrpcRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x1f\n" +
	"\vassignee_id\x18\x02 \x01(\x05R\n" +
	"assigneeId\"M\n" +
	"\x18CreateCommentGrpcRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"l\n" +
	"\x18UpdateCommentGrpcRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x05R\tcommentId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"R\n" +
	"\x18DeleteCommentGrpcRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x05R\tcommentId2\xfc\x13\n" +
	"\x0eProjectService\x12A\n" +
	"\fGetDashboard\x12\x13.projectsvcv1.Empty\x1a\x1c.projectv1.DashboardResponse\x12R\n" +
	"\rCreateProject\x12\x1f.projectv1.CreateProjectRequest\x1a .projectv1.CreateProjectResponse\x12K\n" +
	"\x0fGetProjectTasks\x12\x1e.projectsvcv1.ProjectIdRequest\x1a\x18.projectv1.TasksResponse\x12D\n" +
	"\x0eGetProjectInfo\x12\x1e.projectsvcv1.ProjectIdRequest\x1a\x12.projectv1.Project\x12X\n" +
	"\x11GetProjectMembers\x12\x1e.projectsvcv1.ProjectIdRequest\x1a#.projectv1.ProjectMemberIdsResponse\x12]\n" +
	"\x18GetProjectMembersDetails\x12\x1e.projectsvcv1.ProjectIdRequest\x1a!.projectv1.ProjectMembersResponse\x12P\n" +
	"\x10AddProjectMember\x12\x1e.projectsvcv1.AddMemberRequest\x1a\x1c.projectv1.OperationResponse\x12\\\n" +
	"\x16TransferProjectManager\x12$.projectsvcv1.TransferManagerRequest\x1a\x1c.projectv1.OperationResponse\x12Q\n" +
	"\rIsUserManager\x12\x1e.projectsvcv1.IsManagerRequest\x1a .projectv1.IsUserManagerResponse\x12R\n" +
	"\x0fGetUserProjects\x12!.projectsvcv1.UserProjectsRequest\x1a\x1c.projectv1.DashboardResponse\x12;\n" +
	"\n" +
	"CreateTask\x12\x1c.projectv1.CreateTaskRequest\x1a\x0f.projectv1.Task\x12F\n" +
	"\n" +
	"GetMyTasks\x12\x1e.projectsvcv1.ProjectIdRequest\x1a\x18.projectv1.TasksResponse\x12N\n" +
	"\x12GetAllProjectTasks\x12\x1e.projectsvcv1.ProjectIdRequest\x1a\x18.projectv1.TasksResponse\x12Q\n" +
	"\x15GetClosedProjectTasks\x12\x1e.projectsvcv1.ProjectIdRequest\x1a\x18.projectv1.TasksResponse\x12[\n" +
	"\x10UpdateTaskStatus\x12).projectsvcv1.UpdateTaskStatusGrpcRequest\x1a\x1c.projectv1.OperationResponse\x12F\n" +
	"\tCloseTask\x12\x1b.projectsvcv1.TaskIdRequest\x1a\x1c.projectv1.OperationResponse\x12O\n" +
	"\n" +
	"AssignTask\x12#.projectsvcv1.AssignTaskGrpcRequest\x1a\x1c.projectv1.OperationResponse\x12I\n" +
	"\fUnassignTask\x12\x1b.projectsvcv1.TaskIdRequest\x1a\x1c.projectv1.OperationResponse\x12G\n" +
	"\n" +
	"DeleteTask\x12\x1b.projectsvcv1.TaskIdRequest\x1a\x1c.projectv1.OperationResponse\x12K\n" +
	"\x0fGetTaskComments\x12\x1b.projectsvcv1.TaskIdRequest\x1a\x1b.projectv1.CommentsResponse\x12K\n" +
	"\rCreateComment\x12&.projectsvcv1.CreateCommentGrpcRequest\x1a\x12.projectv1.Comment\x12U\n" +
	"\rUpdateComment\x12&.projectsvcv1.UpdateCommentGrpcRequest\x1a\x1c.projectv1.OperationResponse\x12U\n" +
	"\rDeleteComment\x12&.projectsvcv1.DeleteCommentGrpcRequest\x1a\x1c.projectv1.OperationResponse\x12C\n" +
	"\x0fAdminGetProject\x12\x1c.projectv1.GetProjectRequest\x1a\x12.projectv1.Project\x12S\n" +
	"\x12AdminUpdateProject\x12\x1f.projectv1.UpdateProjectRequest\x1a\x1c.projectv1.OperationResponse\x12S\n" +
	"\x12AdminDeleteProject\x12\x1f.projectv1.DeleteProjectRequest\x1a\x1c.projectv1.OperationResponse\x12:\n" +
	"\fAdminGetTask\x12\x19.projectv1.GetTaskRequest\x1a\x0f.projectv1.Task\x12M\n" +
	"\x0fAdminUpdateTask\x12\x1c.projectv1.UpdateTaskRequest\x1a\x1c.projectv1.OperationResponse\x12M\n" +
	"\x0fAdminDeleteTask\x12\x1c.projectv1.DeleteTaskRequest\x1a\x1c.projectv1.OperationResponse\x12C\n" +
	"\x0fAdminGetComment\x12\x1c.projectv1.GetCommentRequest\x1a\x12.projectv1.Comment\x12S\n" +
	"\x12AdminUpdateComment\x12\x1f.projectv1.UpdateCommentRequest\x1a\x1c.projectv1.OperationResponse\x12S\n" +
	"\x12AdminDeleteComment\x12\x1f.projectv1.DeleteCommentRequest\x1a\x1c.projectv1.OperationResponseB(Z&project-service/api/proto/projectsvcv1b\x06proto3"

var (
	file_project_service_proto_rawDescOnce sync.Once
	file_project_service_proto_rawDescData []byte
)

func file_project_service_proto_rawDescGZIP() []byte {
	file_project_service_proto_rawDescOnce.Do(func() {
		file_project_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_service_proto_rawDesc), len(file_project_service_proto_rawDesc)))
	})
	return file_project_service_proto_rawDescData
}

var file_project_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_project_service_proto_goTypes = []any{
	(*Empty)(nil),                              // 0: projectsvcv1.Empty
	(*ProjectIdRequest)(nil),                   // 1: projectsvcv1.ProjectIdRequest
	(*TaskIdRequest)(nil),                      // 2: projectsvcv1.TaskIdRequest
	(*UserProjectsRequest)(nil),                // 3: projectsvcv1.UserProjectsRequest
	(*AddMemberRequest)(nil),                   // 4: projectsvcv1.AddMemberRequest
	(*TransferManagerRequest)(nil),             // 5: projectsvcv1.TransferManagerRequest
	(*IsManagerRequest)(nil),                   // 6: projectsvcv1.IsManagerRequest
	(*UpdateTaskStatusGrpcRequest)(nil),        // 7: projectsvcv1.UpdateTaskStatusGrpcRequest
	(*AssignTaskGrpcRequest)(nil),              // 8: projectsvcv1.AssignTaskGrpcRequest
	(*CreateCommentGrpcRequest)(nil),           // 9: projectsvcv1.CreateCommentGrpcRequest
	(*UpdateCommentGrpcRequest)(nil),           // 10: projectsvcv1.UpdateCommentGrpcRequest
	(*DeleteCommentGrpcRequest)(nil),           // 11: projectsvcv1.DeleteCommentGrpcRequest
	(projectv1.TaskStatus)(0),                  // 12: projectv1.TaskStatus
	(*projectv1.CreateProjectRequest)(nil),     // 13: projectv1.CreateProjectRequest
	(*projectv1.CreateTaskRequest)(nil),        // 14: projectv1.CreateTaskRequest
	(*projectv1.GetProjectRequest)(nil),        // 15: projectv1.GetProjectRequest
	(*projectv1.UpdateProjectRequest)(nil),     // 16: projectv1.UpdateProjectRequest
	(*projectv1.DeleteProjectRequest)(nil),     // 17: projectv1.DeleteProjectRequest
	(*projectv1.GetTaskRequest)(nil),           // 18: projectv1.GetTaskRequest
	(*projectv1.UpdateTaskRequest)(nil),        // 19: projectv1.UpdateTaskRequest
	(*projectv1.DeleteTaskRequest)(nil),        // 20: projectv1.DeleteTaskRequest
	(*projectv1.GetCommentRequest)(nil),        // 21: projectv1.GetCommentRequest
	(*projectv1.UpdateCommentRequest)(nil),     // 22: projectv1.UpdateCommentRequest
	(*projectv1.DeleteCommentRequest)(nil),     // 23: projectv1.DeleteCommentRequest
	(*projectv1.DashboardResponse)(nil),        // 24: projectv1.DashboardResponse
	(*projectv1.CreateProjectResponse)(nil),    // 25: projectv1.CreateProjectResponse
	(*projectv1.TasksResponse)(nil),            // 26: projectv1.TasksResponse
	(*projectv1.Project)(nil),                  // 27: projectv1.Project
	(*projectv1.ProjectMemberIdsResponse)(nil), // 28: projectv1.ProjectMemberIdsResponse
	(*projectv1.ProjectMembersResponse)(nil),   // 29: projectv1.ProjectMembersResponse
	(*projectv1.OperationResponse)(nil),        // 30: projectv1.OperationResponse
	(*projectv1.IsUserManagerResponse)(nil),    // 31: projectv1.IsUserManagerResponse
	(*projectv1.Task)(nil),                     // 32: projectv1.Task
	(*projectv1.CommentsResponse)(nil),         // 33: projectv1.CommentsResponse
	(*projectv1.Comment)(nil),                  // 34: projectv1.Comment
}
var file_project_service_proto_depIdxs = []int32{
	12, // 0: projectsvcv1.UpdateTaskStatusGrpcRequest.status:type_name -> projectv1.TaskStatus
	0,  // 1: projectsvcv1.ProjectService.GetDashboard:input_type -> projectsvcv1.Empty
	13, // 2: projectsvcv1.ProjectService.CreateProject:input_type -> projectv1.CreateProjectRequest
	1,  // 3: projectsvcv1.ProjectService.GetProjectTasks:input_type -> projectsvcv1.ProjectIdRequest
	1,  // 4: projectsvcv1.ProjectService.GetProjectInfo:input_type -> projectsvcv1.ProjectIdRequest
	1,  // 5: projectsvcv1.ProjectService.GetProjectMembers:input_type -> projectsvcv1.ProjectIdRequest
	1,  // 6: projectsvcv1.ProjectService.GetProjectMembersDetails:input_type -> projectsvcv1.ProjectIdRequest
	4,  // 7: projectsvcv1.ProjectService.AddProjectMember:input_type -> projectsvcv1.AddMemberRequest
	5,  // 8: projectsvcv1.ProjectService.TransferProjectManager:input_type -> projectsvcv1.TransferManagerRequest
	6,  // 9: projectsvcv1.ProjectService.IsUserManager:input_type -> projectsvcv1.IsManagerRequest
	3,  // 10: projectsvcv1.ProjectService.GetUserProjects:input_type -> projectsvcv1.UserProjectsRequest
	14, // 11: projectsvcv1.ProjectService.CreateTask:input_type -> projectv1.CreateTaskRequest
	1,  // 12: projectsvcv1.ProjectService.GetMyTasks:input_type -> projectsvcv1.ProjectIdRequest
	1,  // 13: projectsvcv1.ProjectService.GetAllProjectTasks:input_type -> projectsvcv1.ProjectIdRequest
	1,  // 14: projectsvcv1.ProjectService.GetClosedProjectTasks:input_type -> projectsvcv1.ProjectIdRequest
	7,  // 15: projectsvcv1.ProjectService.UpdateTaskStatus:input_type -> projectsvcv1.UpdateTaskStatusGrpcRequest
	2,  // 16: projectsvcv1.ProjectService.CloseTask:input_type -> projectsvcv1.TaskIdRequest
	8,  // 17: projectsvcv1.ProjectService.AssignTask:input_type -> projectsvcv1.AssignTaskGrpcRequest
	2,  // 18: projectsvcv1.ProjectService.UnassignTask:input_type -> projectsvcv1.TaskIdRequest
	2,  // 19: projectsvcv1.ProjectService.DeleteTask:input_type -> projectsvcv1.TaskIdRequest
	2,  // 20: projectsvcv1.ProjectService.GetTaskComments:input_type -> projectsvcv1.TaskIdRequest
	9,  // 21: projectsvcv1.ProjectService.CreateComment:input_type -> projectsvcv1.CreateCommentGrpcRequest
	10, // 22: projectsvcv1.ProjectService.UpdateComment:input_type -> projectsvcv1.UpdateCommentGrpcRequest
	11, // 23: projectsvcv1.ProjectService.DeleteComment:input_type -> projectsvcv1.DeleteCommentGrpcRequest
	15, // 24: projectsvcv1.ProjectService.AdminGetProject:input_type -> projectv1.GetProjectRequest
	16, // 25: projectsvcv1.ProjectService.AdminUpdateProject:input_type -> projectv1.UpdateProjectRequest
	17, // 26: projectsvcv1.ProjectService.AdminDeleteProject:input_type -> projectv1.DeleteProjectRequest
	18, // 27: projectsvcv1.ProjectService.AdminGetTask:input_type -> projectv1.GetTaskRequest
	19, // 28: projectsvcv1.ProjectService.AdminUpdateTask:input_type -> projectv1.UpdateTaskRequest
	20, // 29: projectsvcv1.ProjectService.AdminDeleteTask:input_type -> projectv1.DeleteTaskRequest
	21, // 30: projectsvcv1.ProjectService.AdminGetComment:input_type -> projectv1.GetCommentRequest
	22, // 31: projectsvcv1.ProjectService.AdminUpdateComment:input_type -> projectv1.UpdateCommentRequest
	23, // 32: projectsvcv1.ProjectService.AdminDeleteComment:input_type -> projectv1.DeleteCommentRequest
	24, // 33: projectsvcv1.ProjectService.GetDashboard:output_type -> projectv1.DashboardResponse
	25, // 34: projectsvcv1.ProjectService.CreateProject:output_type -> projectv1.CreateProjectResponse
	26, // 35: projectsvcv1.ProjectService.GetProjectTasks:output_type -> projectv1.TasksResponse
	27, // 36: projectsvcv1.ProjectService.GetProjectInfo:output_type -> projectv1.Project
	28, // 37: projectsvcv1.ProjectService.GetProjectMembers:output_type -> projectv1.ProjectMemberIdsResponse
	29, // 38: projectsvcv1.ProjectService.GetProjectMembersDetails:output_type -> projectv1.ProjectMembersResponse
	30, // 39: projectsvcv1.ProjectService.AddProjectMember:output_type -> projectv1.OperationResponse
	30, // 40: projectsvcv1.ProjectService.TransferProjectManager:output_type -> projectv1.OperationResponse
	31, // 41: projectsvcv1.ProjectService.IsUserManager:output_type -> projectv1.IsUserManagerResponse
	24, // 42: projectsvcv1.ProjectService.GetUserProjects:output_type -> projectv1.DashboardResponse
	32, // 43: projectsvcv1.ProjectService.CreateTask:output_type -> projectv1.Task
	26, // 44: projectsvcv1.ProjectService.GetMyTasks:output_type -> projectv1.TasksResponse
	26, // 45: projectsvcv1.ProjectService.GetAllProjectTasks:output_type -> projectv1.TasksResponse
	26, // 46: projectsvcv1.ProjectService.GetClosedProjectTasks:output_type -> projectv1.TasksResponse
	30, // 47: projectsvcv1.ProjectService.UpdateTaskStatus:output_type -> projectv1.OperationResponse
	30, // 48: projectsvcv1.ProjectService.CloseTask:output_type -> projectv1.OperationResponse
	30, // 49: projectsvcv1.ProjectService.AssignTask:output_type -> projectv1.OperationResponse
	30, // 50: projectsvcv1.ProjectService.UnassignTask:output_type -> projectv1.OperationResponse
	30, // 51: projectsvcv1.ProjectService.DeleteTask:output_type -> projectv1.OperationResponse
	33, // 52: projectsvcv1.ProjectService.GetTaskComments:output_type -> projectv1.CommentsResponse
	34, // 53: projectsvcv1.ProjectService.CreateComment:output_type -> projectv1.Comment
	30, // 54: projectsvcv1.ProjectService.UpdateComment:output_type -> projectv1.OperationResponse
	30, // 55: projectsvcv1.ProjectService.DeleteComment:output_type -> projectv1.OperationResponse
	27, // 56: projectsvcv1.ProjectService.AdminGetProject:output_type -> projectv1.Project
	30, // 57: projectsvcv1.ProjectService.AdminUpdateProject:output_type -> projectv1.OperationResponse
	30, // 58: projectsvcv1.ProjectService.AdminDeleteProject:output_type -> projectv1.OperationResponse
	32, // 59: projectsvcv1.ProjectService.AdminGetTask:output_type -> projectv1.Task
	30, // 60: projectsvcv1.ProjectService.AdminUpdateTask:output_type -> projectv1.OperationResponse
	30, // 61: projectsvcv1.ProjectService.AdminDeleteTask:output_type -> projectv1.OperationResponse
	34, // 62: projectsvcv1.ProjectService.AdminGetComment:output_type -> projectv1.Comment
	30, // 63: projectsvcv1.ProjectService.AdminUpdateComment:output_type -> projectv1.OperationResponse
	30, // 64: projectsvcv1.ProjectService.AdminDeleteComment:output_type -> projectv1.OperationResponse
	33, // [33:65] is the sub-list for method output_type
	1,  // [1:33] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_project_service_proto_init() }
func file_project_service_proto_init() {
	if File_project_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_service_proto_rawDesc), len(file_project_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_project_service_proto_goTypes,
		DependencyIndexes: file_project_service_proto_depIdxs,
		MessageInfos:      file_project_service_proto_msgTypes,
	}.Build()
	File_project_service_proto = out.File
	file_project_service_proto_goTypes = nil
	file_project_service_proto_depIdxs = nil
}
