// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: project_service.proto

package projectsvcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	projectv1 "project-service/api/proto/projectv1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectService_GetDashboard_FullMethodName             = "/projectsvcv1.ProjectService/GetDashboard"
	ProjectService_CreateProject_FullMethodName            = "/projectsvcv1.ProjectService/CreateProject"
	ProjectService_GetProjectTasks_FullMethodName          = "/projectsvcv1.ProjectService/GetProjectTasks"
	ProjectService_GetProjectInfo_FullMethodName           = "/projectsvcv1.ProjectService/GetProjectInfo"
	ProjectService_GetProjectMembers_FullMethodName        = "/projectsvcv1.ProjectService/GetProjectMembers"
	ProjectService_GetProjectMembersDetails_FullMethodName = "/projectsvcv1.ProjectService/GetProjectMembersDetails"
	ProjectService_AddProjectMember_FullMethodName         = "/projectsvcv1.ProjectService/AddProjectMember"
	ProjectService_TransferProjectManager_FullMethodName   = "/projectsvcv1.ProjectService/TransferProjectManager"
	ProjectService_IsUserManager_FullMethodName            = "/projectsvcv1.ProjectService/IsUserManager"
	ProjectService_GetUserProjects_FullMethodName          = "/projectsvcv1.ProjectService/GetUserProjects"
	ProjectService_CreateTask_FullMethodName               = "/projectsvcv1.ProjectService/CreateTask"
	ProjectService_GetMyTasks_FullMethodName               = "/projectsvcv1.ProjectService/GetMyTasks"
	ProjectService_GetAllProjectTasks_FullMethodName       = "/projectsvcv1.ProjectService/GetAllProjectTasks"
	ProjectService_GetClosedProjectTasks_FullMethodName    = "/projectsvcv1.ProjectService/GetClosedProjectTasks"
	ProjectService_UpdateTaskStatus_FullMethodName         = "/projectsvcv1.ProjectService/UpdateTaskStatus"
	ProjectService_CloseTask_FullMethodName                = "/projectsvcv1.ProjectService/CloseTask"
	ProjectService_AssignTask_FullMethodName               = "/projectsvcv1.ProjectService/AssignTask"
	ProjectService_UnassignTask_FullMethodName             = "/projectsvcv1.ProjectService/UnassignTask"
	ProjectService_DeleteTask_FullMethodName               = "/projectsvcv1.ProjectService/DeleteTask"
	ProjectService_GetTaskComments_FullMethodName          = "/projectsvcv1.ProjectService/GetTaskComments"
	ProjectService_CreateComment_FullMethodName            = "/projectsvcv1.ProjectService/CreateComment"
	ProjectService_UpdateComment_FullMethodName            = "/projectsvcv1.ProjectService/UpdateComment"
	ProjectService_DeleteComment_FullMethodName            = "/projectsvcv1.ProjectService/DeleteComment"
	ProjectService_AdminGetProject_FullMethodName          = "/projectsvcv1.ProjectService/AdminGetProject"
	ProjectService_AdminUpdateProject_FullMethodName       = "/projectsvcv1.ProjectService/AdminUpdateProject"
	ProjectService_AdminDeleteProject_FullMethodName       = "/projectsvcv1.ProjectService/AdminDeleteProject"
	ProjectService_AdminGetTask_FullMethodName             = "/projectsvcv1.ProjectService/AdminGetTask"
	ProjectService_AdminUpdateTask_FullMethodName          = "/projectsvcv1.ProjectService/AdminUpdateTask"
	ProjectService_AdminDeleteTask_FullMethodName          = "/projectsvcv1.ProjectService/AdminDeleteTask"
	ProjectService_AdminGetComment_FullMethodName          = "/projectsvcv1.ProjectService/AdminGetComment"
	ProjectService_AdminUpdateComment_FullMethodName       = "/projectsvcv1.ProjectService/AdminUpdateComment"
	ProjectService_AdminDeleteComment_FullMethodName       = "/projectsvcv1.ProjectService/AdminDeleteComment"
)

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProjectService defines the internal gRPC interface for the project-service.
// This is NOT the external API — external API is described in api-gateway/api/openapi.yaml.
type ProjectServiceClient interface {
	// --- Dashboard ---
	GetDashboard(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*projectv1.DashboardResponse, error)
	// --- Projects ---
	CreateProject(ctx context.Context, in *projectv1.CreateProjectRequest, opts ...grpc.CallOption) (*projectv1.CreateProjectResponse, error)
	GetProjectTasks(ctx context.Context, in *ProjectIdRequest, opts ...grpc.CallOption) (*projectv1.TasksResponse, error)
	GetProjectInfo(ctx context.Context, in *ProjectIdRequest, opts ...grpc.CallOption) (*projectv1.Project, error)
	GetProjectMembers(ctx context.Context, in *ProjectIdRequest, opts ...grpc.CallOption) (*projectv1.ProjectMemberIdsResponse, error)
	GetProjectMembersDetails(ctx context.Context, in *ProjectIdRequest, opts ...grpc.CallOption) (*projectv1.ProjectMembersResponse, error)
	AddProjectMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
	TransferProjectManager(ctx context.Context, in *TransferManagerRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
	IsUserManager(ctx context.Context, in *IsManagerRequest, opts ...grpc.CallOption) (*projectv1.IsUserManagerResponse, error)
	GetUserProjects(ctx context.Context, in *UserProjectsRequest, opts ...grpc.CallOption) (*projectv1.DashboardResponse, error)
	// --- Tasks ---
	CreateTask(ctx context.Context, in *projectv1.CreateTaskRequest, opts ...grpc.CallOption) (*projectv1.Task, error)
	GetMyTasks(ctx context.Context, in *ProjectIdRequest, opts ...grpc.CallOption) (*projectv1.TasksResponse, error)
	GetAllProjectTasks(ctx context.Context, in *ProjectIdRequest, opts ...grpc.CallOption) (*projectv1.TasksResponse, error)
	GetClosedProjectTasks(ctx context.Context, in *ProjectIdRequest, opts ...grpc.CallOption) (*projectv1.TasksResponse, error)
	UpdateTaskStatus(ctx context.Context, in *UpdateTaskStatusGrpcRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
	CloseTask(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
	AssignTask(ctx context.Context, in *AssignTaskGrpcRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
	UnassignTask(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
	DeleteTask(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
	// --- Comments ---
	GetTaskComments(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*projectv1.CommentsResponse, error)
	CreateComment(ctx context.Context, in *CreateCommentGrpcRequest, opts ...grpc.CallOption) (*projectv1.Comment, error)
	UpdateComment(ctx context.Context, in *UpdateCommentGrpcRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
	DeleteComment(ctx context.Context, in *DeleteCommentGrpcRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
	// --- Admin ---
	AdminGetProject(ctx context.Context, in *projectv1.GetProjectRequest, opts ...grpc.CallOption) (*projectv1.Project, error)
	AdminUpdateProject(ctx context.Context, in *projectv1.UpdateProjectRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
	AdminDeleteProject(ctx context.Context, in *projectv1.DeleteProjectRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
	AdminGetTask(ctx context.Context, in *projectv1.GetTaskRequest, opts ...grpc.CallOption) (*projectv1.Task, error)
	AdminUpdateTask(ctx context.Context, in *projectv1.UpdateTaskRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
	AdminDeleteTask(ctx context.Context, in *projectv1.DeleteTaskRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
	AdminGetComment(ctx context.Context, in *projectv1.GetCommentRequest, opts ...grpc.CallOption) (*projectv1.Comment, error)
	AdminUpdateComment(ctx context.Context, in *projectv1.UpdateCommentRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
	AdminDeleteComment(ctx context.Context, in *projectv1.DeleteCommentRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error)
}

type projectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) GetDashboard(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*projectv1.DashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.DashboardResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) CreateProject(ctx context.Context, in *projectv1.CreateProjectRequest, opts ...grpc.CallOption) (*projectv1.CreateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.CreateProjectResponse)
	err := c.cc.Invoke(ctx, ProjectService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectTasks(ctx context.Context, in *ProjectIdRequest, opts ...grpc.CallOption) (*projectv1.TasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.TasksResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetProjectTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectInfo(ctx context.Context, in *ProjectIdRequest, opts ...grpc.CallOption) (*projectv1.Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.Project)
	err := c.cc.Invoke(ctx, ProjectService_GetProjectInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectMembers(ctx context.Context, in *ProjectIdRequest, opts ...grpc.CallOption) (*projectv1.ProjectMemberIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.ProjectMemberIdsResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetProjectMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectMembersDetails(ctx context.Context, in *ProjectIdRequest, opts ...grpc.CallOption) (*projectv1.ProjectMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.ProjectMembersResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetProjectMembersDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AddProjectMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_AddProjectMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) TransferProjectManager(ctx context.Context, in *TransferManagerRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_TransferProjectManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) IsUserManager(ctx context.Context, in *IsManagerRequest, opts ...grpc.CallOption) (*projectv1.IsUserManagerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.IsUserManagerResponse)
	err := c.cc.Invoke(ctx, ProjectService_IsUserManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetUserProjects(ctx context.Context, in *UserProjectsRequest, opts ...grpc.CallOption) (*projectv1.DashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.DashboardResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetUserProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) CreateTask(ctx context.Context, in *projectv1.CreateTaskRequest, opts ...grpc.CallOption) (*projectv1.Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.Task)
	err := c.cc.Invoke(ctx, ProjectService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetMyTasks(ctx context.Context, in *ProjectIdRequest, opts ...grpc.CallOption) (*projectv1.TasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.TasksResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetMyTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetAllProjectTasks(ctx context.Context, in *ProjectIdRequest, opts ...grpc.CallOption) (*projectv1.TasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.TasksResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetAllProjectTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetClosedProjectTasks(ctx context.Context, in *ProjectIdRequest, opts ...grpc.CallOption) (*projectv1.TasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.TasksResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetClosedProjectTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateTaskStatus(ctx context.Context, in *UpdateTaskStatusGrpcRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_UpdateTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) CloseTask(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_CloseTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AssignTask(ctx context.Context, in *AssignTaskGrpcRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_AssignTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UnassignTask(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_UnassignTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DeleteTask(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetTaskComments(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*projectv1.CommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.CommentsResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetTaskComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) CreateComment(ctx context.Context, in *CreateCommentGrpcRequest, opts ...grpc.CallOption) (*projectv1.Comment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.Comment)
	err := c.cc.Invoke(ctx, ProjectService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateComment(ctx context.Context, in *UpdateCommentGrpcRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_UpdateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentGrpcRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AdminGetProject(ctx context.Context, in *projectv1.GetProjectRequest, opts ...grpc.CallOption) (*projectv1.Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.Project)
	err := c.cc.Invoke(ctx, ProjectService_AdminGetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AdminUpdateProject(ctx context.Context, in *projectv1.UpdateProjectRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_AdminUpdateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AdminDeleteProject(ctx context.Context, in *projectv1.DeleteProjectRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_AdminDeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AdminGetTask(ctx context.Context, in *projectv1.GetTaskRequest, opts ...grpc.CallOption) (*projectv1.Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.Task)
	err := c.cc.Invoke(ctx, ProjectService_AdminGetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AdminUpdateTask(ctx context.Context, in *projectv1.UpdateTaskRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_AdminUpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AdminDeleteTask(ctx context.Context, in *projectv1.DeleteTaskRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_AdminDeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AdminGetComment(ctx context.Context, in *projectv1.GetCommentRequest, opts ...grpc.CallOption) (*projectv1.Comment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.Comment)
	err := c.cc.Invoke(ctx, ProjectService_AdminGetComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AdminUpdateComment(ctx context.Context, in *projectv1.UpdateCommentRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_AdminUpdateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AdminDeleteComment(ctx context.Context, in *projectv1.DeleteCommentRequest, opts ...grpc.CallOption) (*projectv1.OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(projectv1.OperationResponse)
	err := c.cc.Invoke(ctx, ProjectService_AdminDeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
// All implementations must embed UnimplementedProjectServiceServer
// for forward compatibility.
//
// ProjectService defines the internal gRPC interface for the project-service.
// This is NOT the external API — external API is described in api-gateway/api/openapi.yaml.
type ProjectServiceServer interface {
	// --- Dashboard ---
	GetDashboard(context.Context, *Empty) (*projectv1.DashboardResponse, error)
	// --- Projects ---
	CreateProject(context.Context, *projectv1.CreateProjectRequest) (*projectv1.CreateProjectResponse, error)
	GetProjectTasks(context.Context, *ProjectIdRequest) (*projectv1.TasksResponse, error)
	GetProjectInfo(context.Context, *ProjectIdRequest) (*projectv1.Project, error)
	GetProjectMembers(context.Context, *ProjectIdRequest) (*projectv1.ProjectMemberIdsResponse, error)
	GetProjectMembersDetails(context.Context, *ProjectIdRequest) (*projectv1.ProjectMembersResponse, error)
	AddProjectMember(context.Context, *AddMemberRequest) (*projectv1.OperationResponse, error)
	TransferProjectManager(context.Context, *TransferManagerRequest) (*projectv1.OperationResponse, error)
	IsUserManager(context.Context, *IsManagerRequest) (*projectv1.IsUserManagerResponse, error)
	GetUserProjects(context.Context, *UserProjectsRequest) (*projectv1.DashboardResponse, error)
	// --- Tasks ---
	CreateTask(context.Context, *projectv1.CreateTaskRequest) (*projectv1.Task, error)
	GetMyTasks(context.Context, *ProjectIdRequest) (*projectv1.TasksResponse, error)
	GetAllProjectTasks(context.Context, *ProjectIdRequest) (*projectv1.TasksResponse, error)
	GetClosedProjectTasks(context.Context, *ProjectIdRequest) (*projectv1.TasksResponse, error)
	UpdateTaskStatus(context.Context, *UpdateTaskStatusGrpcRequest) (*projectv1.OperationResponse, error)
	CloseTask(context.Context, *TaskIdRequest) (*projectv1.OperationResponse, error)
	AssignTask(context.Context, *AssignTaskGrpcRequest) (*projectv1.OperationResponse, error)
	UnassignTask(context.Context, *TaskIdRequest) (*projectv1.OperationResponse, error)
	DeleteTask(context.Context, *TaskIdRequest) (*projectv1.OperationResponse, error)
	// --- Comments ---
	GetTaskComments(context.Context, *TaskIdRequest) (*projectv1.CommentsResponse, error)
	CreateComment(context.Context, *CreateCommentGrpcRequest) (*projectv1.Comment, error)
	UpdateComment(context.Context, *UpdateCommentGrpcRequest) (*projectv1.OperationResponse, error)
	DeleteComment(context.Context, *DeleteCommentGrpcRequest) (*projectv1.OperationResponse, error)
	// --- Admin ---
	AdminGetProject(context.Context, *projectv1.GetProjectRequest) (*projectv1.Project, error)
	AdminUpdateProject(context.Context, *projectv1.UpdateProjectRequest) (*projectv1.OperationResponse, error)
	AdminDeleteProject(context.Context, *projectv1.DeleteProjectRequest) (*projectv1.OperationResponse, error)
	AdminGetTask(context.Context, *projectv1.GetTaskRequest) (*projectv1.Task, error)
	AdminUpdateTask(context.Context, *projectv1.UpdateTaskRequest) (*projectv1.OperationResponse, error)
	AdminDeleteTask(context.Context, *projectv1.DeleteTaskRequest) (*projectv1.OperationResponse, error)
	AdminGetComment(context.Context, *projectv1.GetCommentRequest) (*projectv1.Comment, error)
	AdminUpdateComment(context.Context, *projectv1.UpdateCommentRequest) (*projectv1.OperationResponse, error)
	AdminDeleteComment(context.Context, *projectv1.DeleteCommentRequest) (*projectv1.OperationResponse, error)
	mustEmbedUnimplementedProjectServiceServer()
}

// UnimplementedProjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectServiceServer struct{}

func (UnimplementedProjectServiceServer) GetDashboard(context.Context, *Empty) (*projectv1.DashboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedProjectServiceServer) CreateProject(context.Context, *projectv1.CreateProjectRequest) (*projectv1.CreateProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectTasks(context.Context, *ProjectIdRequest) (*projectv1.TasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectTasks not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectInfo(context.Context, *ProjectIdRequest) (*projectv1.Project, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectInfo not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectMembers(context.Context, *ProjectIdRequest) (*projectv1.ProjectMemberIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectMembers not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectMembersDetails(context.Context, *ProjectIdRequest) (*projectv1.ProjectMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectMembersDetails not implemented")
}
func (UnimplementedProjectServiceServer) AddProjectMember(context.Context, *AddMemberRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddProjectMember not implemented")
}
func (UnimplementedProjectServiceServer) TransferProjectManager(context.Context, *TransferManagerRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferProjectManager not implemented")
}
func (UnimplementedProjectServiceServer) IsUserManager(context.Context, *IsManagerRequest) (*projectv1.IsUserManagerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsUserManager not implemented")
}
func (UnimplementedProjectServiceServer) GetUserProjects(context.Context, *UserProjectsRequest) (*projectv1.DashboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProjects not implemented")
}
func (UnimplementedProjectServiceServer) CreateTask(context.Context, *projectv1.CreateTaskRequest) (*projectv1.Task, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedProjectServiceServer) GetMyTasks(context.Context, *ProjectIdRequest) (*projectv1.TasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyTasks not implemented")
}
func (UnimplementedProjectServiceServer) GetAllProjectTasks(context.Context, *ProjectIdRequest) (*projectv1.TasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllProjectTasks not implemented")
}
func (UnimplementedProjectServiceServer) GetClosedProjectTasks(context.Context, *ProjectIdRequest) (*projectv1.TasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClosedProjectTasks not implemented")
}
func (UnimplementedProjectServiceServer) UpdateTaskStatus(context.Context, *UpdateTaskStatusGrpcRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTaskStatus not implemented")
}
func (UnimplementedProjectServiceServer) CloseTask(context.Context, *TaskIdRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseTask not implemented")
}
func (UnimplementedProjectServiceServer) AssignTask(context.Context, *AssignTaskGrpcRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignTask not implemented")
}
func (UnimplementedProjectServiceServer) UnassignTask(context.Context, *TaskIdRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnassignTask not implemented")
}
func (UnimplementedProjectServiceServer) DeleteTask(context.Context, *TaskIdRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedProjectServiceServer) GetTaskComments(context.Context, *TaskIdRequest) (*projectv1.CommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskComments not implemented")
}
func (UnimplementedProjectServiceServer) CreateComment(context.Context, *CreateCommentGrpcRequest) (*projectv1.Comment, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedProjectServiceServer) UpdateComment(context.Context, *UpdateCommentGrpcRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedProjectServiceServer) DeleteComment(context.Context, *DeleteCommentGrpcRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedProjectServiceServer) AdminGetProject(context.Context, *projectv1.GetProjectRequest) (*projectv1.Project, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminGetProject not implemented")
}
func (UnimplementedProjectServiceServer) AdminUpdateProject(context.Context, *projectv1.UpdateProjectRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUpdateProject not implemented")
}
func (UnimplementedProjectServiceServer) AdminDeleteProject(context.Context, *projectv1.DeleteProjectRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeleteProject not implemented")
}
func (UnimplementedProjectServiceServer) AdminGetTask(context.Context, *projectv1.GetTaskRequest) (*projectv1.Task, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminGetTask not implemented")
}
func (UnimplementedProjectServiceServer) AdminUpdateTask(context.Context, *projectv1.UpdateTaskRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUpdateTask not implemented")
}
func (UnimplementedProjectServiceServer) AdminDeleteTask(context.Context, *projectv1.DeleteTaskRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeleteTask not implemented")
}
func (UnimplementedProjectServiceServer) AdminGetComment(context.Context, *projectv1.GetCommentRequest) (*projectv1.Comment, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminGetComment not implemented")
}
func (UnimplementedProjectServiceServer) AdminUpdateComment(context.Context, *projectv1.UpdateCommentRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUpdateComment not implemented")
}
func (UnimplementedProjectServiceServer) AdminDeleteComment(context.Context, *projectv1.DeleteCommentRequest) (*projectv1.OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeleteComment not implemented")
}
func (UnimplementedProjectServiceServer) mustEmbedUnimplementedProjectServiceServer() {}
func (UnimplementedProjectServiceServer) testEmbeddedByValue()                        {}

// UnsafeProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServiceServer will
// result in compilation errors.
type UnsafeProjectServiceServer interface {
	mustEmbedUnimplementedProjectServiceServer()
}

func RegisterProjectServiceServer(s grpc.ServiceRegistrar, srv ProjectServiceServer) {
	// If the following call panics, it indicates UnimplementedProjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectService_ServiceDesc, srv)
}

func _ProjectService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetDashboard(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(projectv1.CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).CreateProject(ctx, req.(*projectv1.CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProjectTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectTasks(ctx, req.(*ProjectIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProjectInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectInfo(ctx, req.(*ProjectIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProjectMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectMembers(ctx, req.(*ProjectIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectMembersDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectMembersDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProjectMembersDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectMembersDetails(ctx, req.(*ProjectIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AddProjectMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AddProjectMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AddProjectMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AddProjectMember(ctx, req.(*AddMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_TransferProjectManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).TransferProjectManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_TransferProjectManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).TransferProjectManager(ctx, req.(*TransferManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_IsUserManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).IsUserManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_IsUserManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).IsUserManager(ctx, req.(*IsManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetUserProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetUserProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetUserProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetUserProjects(ctx, req.(*UserProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(projectv1.CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).CreateTask(ctx, req.(*projectv1.CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetMyTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetMyTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetMyTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetMyTasks(ctx, req.(*ProjectIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetAllProjectTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetAllProjectTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetAllProjectTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetAllProjectTasks(ctx, req.(*ProjectIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetClosedProjectTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetClosedProjectTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetClosedProjectTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetClosedProjectTasks(ctx, req.(*ProjectIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskStatusGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UpdateTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateTaskStatus(ctx, req.(*UpdateTaskStatusGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_CloseTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).CloseTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_CloseTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).CloseTask(ctx, req.(*TaskIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AssignTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTaskGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AssignTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AssignTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AssignTask(ctx, req.(*AssignTaskGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UnassignTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UnassignTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UnassignTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UnassignTask(ctx, req.(*TaskIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DeleteTask(ctx, req.(*TaskIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetTaskComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetTaskComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetTaskComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetTaskComments(ctx, req.(*TaskIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).CreateComment(ctx, req.(*CreateCommentGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateComment(ctx, req.(*UpdateCommentGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DeleteComment(ctx, req.(*DeleteCommentGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AdminGetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(projectv1.GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AdminGetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AdminGetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AdminGetProject(ctx, req.(*projectv1.GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AdminUpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(projectv1.UpdateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AdminUpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AdminUpdateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AdminUpdateProject(ctx, req.(*projectv1.UpdateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AdminDeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(projectv1.DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AdminDeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AdminDeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AdminDeleteProject(ctx, req.(*projectv1.DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AdminGetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(projectv1.GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AdminGetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AdminGetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AdminGetTask(ctx, req.(*projectv1.GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AdminUpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(projectv1.UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AdminUpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AdminUpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AdminUpdateTask(ctx, req.(*projectv1.UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AdminDeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(projectv1.DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AdminDeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AdminDeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AdminDeleteTask(ctx, req.(*projectv1.DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AdminGetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(projectv1.GetCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AdminGetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AdminGetComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AdminGetComment(ctx, req.(*projectv1.GetCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AdminUpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(projectv1.UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AdminUpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AdminUpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AdminUpdateComment(ctx, req.(*projectv1.UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AdminDeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(projectv1.DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AdminDeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AdminDeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AdminDeleteComment(ctx, req.(*projectv1.DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectService_ServiceDesc is the grpc.ServiceDesc for ProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "projectsvcv1.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboard",
			Handler:    _ProjectService_GetDashboard_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _ProjectService_CreateProject_Handler,
		},
		{
			MethodName: "GetProjectTasks",
			Handler:    _ProjectService_GetProjectTasks_Handler,
		},
		{
			MethodName: "GetProjectInfo",
			Handler:    _ProjectService_GetProjectInfo_Handler,
		},
		{
			MethodName: "GetProjectMembers",
			Handler:    _ProjectService_GetProjectMembers_Handler,
		},
		{
			MethodName: "GetProjectMembersDetails",
			Handler:    _ProjectService_GetProjectMembersDetails_Handler,
		},
		{
			MethodName: "AddProjectMember",
			Handler:    _ProjectService_AddProjectMember_Handler,
		},
		{
			MethodName: "TransferProjectManager",
			Handler:    _ProjectService_TransferProjectManager_Handler,
		},
		{
			MethodName: "IsUserManager",
			Handler:    _ProjectService_IsUserManager_Handler,
		},
		{
			MethodName: "GetUserProjects",
			Handler:    _ProjectService_GetUserProjects_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _ProjectService_CreateTask_Handler,
		},
		{
			MethodName: "GetMyTasks",
			Handler:    _ProjectService_GetMyTasks_Handler,
		},
		{
			MethodName: "GetAllProjectTasks",
			Handler:    _ProjectService_GetAllProjectTasks_Handler,
		},
		{
			MethodName: "GetClosedProjectTasks",
			Handler:    _ProjectService_GetClosedProjectTasks_Handler,
		},
		{
			MethodName: "UpdateTaskStatus",
			Handler:    _ProjectService_UpdateTaskStatus_Handler,
		},
		{
			MethodName: "CloseTask",
			Handler:    _ProjectService_CloseTask_Handler,
		},
		{
			MethodName: "AssignTask",
			Handler:    _ProjectService_AssignTask_Handler,
		},
		{
			MethodName: "UnassignTask",
			Handler:    _ProjectService_UnassignTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _ProjectService_DeleteTask_Handler,
		},
		{
			MethodName: "GetTaskComments",
			Handler:    _ProjectService_GetTaskComments_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _ProjectService_CreateComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _ProjectService_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _ProjectService_DeleteComment_Handler,
		},
		{
			MethodName: "AdminGetProject",
			Handler:    _ProjectService_AdminGetProject_Handler,
		},
		{
			MethodName: "AdminUpdateProject",
			Handler:    _ProjectService_AdminUpdateProject_Handler,
		},
		{
			MethodName: "AdminDeleteProject",
			Handler:    _ProjectService_AdminDeleteProject_Handler,
		},
		{
			MethodName: "AdminGetTask",
			Handler:    _ProjectService_AdminGetTask_Handler,
		},
		{
			MethodName: "AdminUpdateTask",
			Handler:    _ProjectService_AdminUpdateTask_Handler,
		},
		{
			MethodName: "AdminDeleteTask",
			Handler:    _ProjectService_AdminDeleteTask_Handler,
		},
		{
			MethodName: "AdminGetComment",
			Handler:    _ProjectService_AdminGetComment_Handler,
		},
		{
			MethodName: "AdminUpdateComment",
			Handler:    _ProjectService_AdminUpdateComment_Handler,
		},
		{
			MethodName: "AdminDeleteComment",
			Handler:    _ProjectService_AdminDeleteComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "project_service.proto",
}
