syntax = "proto3";

package dto;

option go_package = "auth-service/internal/model/dto";

message User {
  int32 id = 1;
  string email = 2;
  string name = 3;
  string surname = 4;
  string role = 5;
  // password is not included for security
}

message Comment {
  int32 id = 1;
  int32 author_id = 2;
  int32 task_id = 3;
  string content = 4;
  string creation_date = 5;
}

message RegisterRequest {
  string email = 1;
  string password = 2;
  string name = 3;
  string surname = 4;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string token = 1;
}

message ValidateTokenRequest {
  string token = 1;
}

message ValidateTokenResponse {
  int32 user_id = 1;
  string role = 2;
}

message GetUserRequest {
  optional int32 user_id = 1;
  optional string email = 2;
}

message UpdateUserRequest {
  User user = 1;
  optional string password = 2;
}

message DeleteUserRequest {
  int32 user_id = 1;
}

message GetCommentRequest {
  optional int32 comment_id = 1;
  optional int32 author_id = 2;
  optional int32 task_id = 3;
}

message UpdateCommentRequest {
  Comment comment = 1;
}

message DeleteCommentRequest {
  int32 comment_id = 1;
}

message OperationResponse {
  string message = 1;
}
