http:
  addr: ":8081"

grpc:
  addr: ":9091"

postgres:
  url: "postgres://postgres:postgres@localhost:5433/project_db?sslmode=disable"

auth_service:
  url: "http://localhost:8080"

static_dir: "../../frontend/project"

shutdown_timeout: 10s
