http:
  addr: ":8081"

grpc:
  addr: ":9091"

postgres:
  url: "postgres://postgres:postgres@db:5432/project_db?sslmode=disable"

auth_service:
  url: "http://auth-service:8080"

static_dir: "/static"

shutdown_timeout: 10s
