// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: auth_service.proto

package authsvcv1

import (
	userv1 "auth-service/api/proto/userv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_service_proto protoreflect.FileDescriptor

const file_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x12auth_service.proto\x12\tauthsvcv1\x1a\n" +
	"user.proto2\xbf\x03\n" +
	"\vAuthService\x12>\n" +
	"\bRegister\x12\x17.userv1.RegisterRequest\x1a\x19.userv1.OperationResponse\x124\n" +
	"\x05Login\x12\x14.userv1.LoginRequest\x1a\x15.userv1.LoginResponse\x12L\n" +
	"\rValidateToken\x12\x1c.userv1.ValidateTokenRequest\x1a\x1d.userv1.ValidateTokenResponse\x123\n" +
	"\vGetUserInfo\x12\x16.userv1.GetUserRequest\x1a\f.userv1.User\x12/\n" +
	"\aGetUser\x12\x16.userv1.GetUserRequest\x1a\f.userv1.User\x12B\n" +
	"\n" +
	"UpdateUser\x12\x19.userv1.UpdateUserRequest\x1a\x19.userv1.OperationResponse\x12B\n" +
	"\n" +
	"DeleteUser\x12\x19.userv1.DeleteUserRequest\x1a\x19.userv1.OperationResponseB\"Z auth-service/api/proto/authsvcv1b\x06proto3"

var file_auth_service_proto_goTypes = []any{
	(*userv1.RegisterRequest)(nil),       // 0: userv1.RegisterRequest
	(*userv1.LoginRequest)(nil),          // 1: userv1.LoginRequest
	(*userv1.ValidateTokenRequest)(nil),  // 2: userv1.ValidateTokenRequest
	(*userv1.GetUserRequest)(nil),        // 3: userv1.GetUserRequest
	(*userv1.UpdateUserRequest)(nil),     // 4: userv1.UpdateUserRequest
	(*userv1.DeleteUserRequest)(nil),     // 5: userv1.DeleteUserRequest
	(*userv1.OperationResponse)(nil),     // 6: userv1.OperationResponse
	(*userv1.LoginResponse)(nil),         // 7: userv1.LoginResponse
	(*userv1.ValidateTokenResponse)(nil), // 8: userv1.ValidateTokenResponse
	(*userv1.User)(nil),                  // 9: userv1.User
}
var file_auth_service_proto_depIdxs = []int32{
	0, // 0: authsvcv1.AuthService.Register:input_type -> userv1.RegisterRequest
	1, // 1: authsvcv1.AuthService.Login:input_type -> userv1.LoginRequest
	2, // 2: authsvcv1.AuthService.ValidateToken:input_type -> userv1.ValidateTokenRequest
	3, // 3: authsvcv1.AuthService.GetUserInfo:input_type -> userv1.GetUserRequest
	3, // 4: authsvcv1.AuthService.GetUser:input_type -> userv1.GetUserRequest
	4, // 5: authsvcv1.AuthService.UpdateUser:input_type -> userv1.UpdateUserRequest
	5, // 6: authsvcv1.AuthService.DeleteUser:input_type -> userv1.DeleteUserRequest
	6, // 7: authsvcv1.AuthService.Register:output_type -> userv1.OperationResponse
	7, // 8: authsvcv1.AuthService.Login:output_type -> userv1.LoginResponse
	8, // 9: authsvcv1.AuthService.ValidateToken:output_type -> userv1.ValidateTokenResponse
	9, // 10: authsvcv1.AuthService.GetUserInfo:output_type -> userv1.User
	9, // 11: authsvcv1.AuthService.GetUser:output_type -> userv1.User
	6, // 12: authsvcv1.AuthService.UpdateUser:output_type -> userv1.OperationResponse
	6, // 13: authsvcv1.AuthService.DeleteUser:output_type -> userv1.OperationResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_service_proto_init() }
func file_auth_service_proto_init() {
	if File_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_service_proto_rawDesc), len(file_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_service_proto_goTypes,
		DependencyIndexes: file_auth_service_proto_depIdxs,
	}.Build()
	File_auth_service_proto = out.File
	file_auth_service_proto_goTypes = nil
	file_auth_service_proto_depIdxs = nil
}
